### ISSUE TITLE
rpc error: code = Unknown desc = process "/bin/sh -c apt-get update &&   apt-get install -y openjdk-17-jre-headless &&   rm -rf /var/lib/apt/lists/* &&   chmod 400 *" did not complete successfully: exit code: 100

### ISSUE THREAD

**Issue by rubencolmenarejo** [retro-game/retro-game#69]
Hi, sorry, I have one error that I don't know to fix:

I executed the command:

docker-compose up

and the installation finishes with

`#6 17.27 head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
#6 17.35 Exception in thread "main" java.lang.InternalError: Error loading java.security file
#6 17.35        at java.base/java.security.Security.initialize(Security.java:106)
#6 17.35        at java.base/java.security.Security$1.run(Security.java:84)
#6 17.35        at java.base/java.security.Security$1.run(Security.java:82)
#6 17.35        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
#6 17.35        at java.base/java.security.Security.<clinit>(Security.java:82)
#6 17.35        at java.base/sun.security.jca.ProviderList.<init>(ProviderList.java:178)
#6 17.35        at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:96)
#6 17.35        at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:94)
#6 17.35        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
#6 17.35        at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:93)
#6 17.35        at java.base/sun.security.jca.Providers.<clinit>(Providers.java:55)
#6 17.35        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
#6 17.35        at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
#6 17.35        at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50)
#6 17.35        at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
#6 17.35        at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
#6 17.37 dpkg: error processing package ca-certificates-java (--configure):
#6 17.37  installed ca-certificates-java package post-installation script subprocess returned error exit status 1
#6 17.37 dpkg: dependency problems prevent configuration of openjdk-17-jre-headless:amd64:
#6 17.37  openjdk-17-jre-headless:amd64 depends on ca-certificates-java (>= 20190405~); however:
#6 17.37   Package ca-certificates-java is not configured yet.
#6 17.37
#6 17.37 dpkg: error processing package openjdk-17-jre-headless:amd64 (--configure):
#6 17.37  dependency problems - leaving unconfigured
#6 17.37 Processing triggers for libc-bin (2.31-13+deb11u6) ...
#6 17.41 Processing triggers for ca-certificates (20210119) ...
#6 17.42 Updating certificates in /etc/ssl/certs...
#6 17.88 0 added, 0 removed; done.
#6 17.88 Running hooks in /etc/ca-certificates/update.d...
#6 17.88
#6 17.91 /etc/ca-certificates/update.d/jks-keystore: 82: java: not found
#6 17.91 E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.
#6 17.91 done.
#6 17.93 Errors were encountered while processing:
#6 17.93  ca-certificates-java
#6 17.93  openjdk-17-jre-headless:amd64
#6 17.95 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
failed to solve: rpc error: code = Unknown desc = process "/bin/sh -c apt-get update &&   apt-get install -y openjdk-17-jre-headless &&   rm -rf /var/lib/apt/lists/* &&   chmod 400 *" did not complete successfully: exit code: 100`

Do you have any idea about how to fix this?

I tried to execute on :

Docker version 24.0.2, build cb74dfc

Thanks in advance.

**Comment by ITECHINN** [comment]
You need to install ca-certificate-java before installing openjdk

```
FROM debian:bullseye-slim AS builder
WORKDIR /retro-game-src
COPY . .
RUN \
  # Install packages needed to build the game.
  apt-get update && \
  apt-get install -y \
    build-essential \
    cmake \
    maven \
    openjdk-17-jdk && \
  rm -rf /var/lib/apt/lists/* && \
  # Build the battle engine.
  JAVA_HOME="$(dirname $(dirname $(readlink -f $(which java))))" cmake -B build -DCMAKE_BUILD_TYPE=Release battle-engine && \
  cmake --build build && \
  # Build the game.
  mvn -B -DskipTests package && \
  rm -rf ~/.m2

FROM debian:bullseye-slim
WORKDIR /retro-game
COPY --from=builder /retro-game-src/build/libBattleEngine.so .
COPY --from=builder /retro-game-src/target/retro-game-*.jar retro-game.jar
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN mkdir -p /etc/ssl/certs/java
RUN \
  # Install packages needed to run the game.
  apt-get update && \
  apt-get install -y --no-install-recommends ca-certificates
RUN update-ca-certificates 
RUN apt-get install -y ca-certificates-java
RUN /var/lib/dpkg/info/ca-certificates-java.postinst configure
RUN apt-get install -y apt-utils openjdk-17-jre-headless && \
  rm -rf /var/lib/apt/lists/* && \
  # Change the permissions of the artifacts.
  chmod 400 *
CMD ["java", "-Djava.library.path=.", "-jar", "retro-game.jar"]
```

Change the dockerfile content as above.

**Comment by gaius1304** [comment]
Assuming this was resolved.
